language: node_js
node_js:
  - '7'
branches:
  only:
    - '/^v[0-9]/'
before_script:
  - yarn run build
  - export NODE_ENV="test"
after_success:
  - npm run coverage
  - 'npm run mocha:json'
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://codecov.octoblu.com/bash)'
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
